#docker-compose.yaml
version: "3.6"
services:
  nginx-cots3:
    image: "registry.infralabs.cs.ui.ac.id/1406568753/law-cots3-nginx:v1"
    build: "./nginx"
    ports:
      - "22106:22106"
    depends_on:
      - "nginxdl-cots3"
      - "goulservice-cots3"
    volumes:
      - "1406568753-law-cots3-storage:/dl"
    networks:
      - "1406568753-law-cots3-network"
  nginxdl-cots3:
    image: "registry.infralabs.cs.ui.ac.id/1406568753/law-cots3-nginxdl:v1"
    build: "./dl-server"
    ports:
      - "23064:23064"
    volumes:
      - "1406568753-law-cots3-storage:/dl"
    networks:
      - "1406568753-law-cots3-network"
  goulservice-cots3:
    image: "registry.infralabs.cs.ui.ac.id/1406568753/law-cots3-ul:v1"
    build: "./ul-server"
    ports:
      - "23063:23063"
    volumes:
      - "1406568753-law-cots3-storage:/dl"
    networks:
      - "1406568753-law-cots3-network"
volumes:
  1406568753-law-cots3-storage:
networks:
  1406568753-law-cots3-network: